# Generated by Django 6.0.7 on 2026-07-25 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='directors/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hope Reception Centre', max_length=200)),
                ('tagline', models.CharField(default='Giving Hope to Children Since 2003', max_length=255)),
                ('established_year', models.IntegerField(default=2003)),
                ('address', models.TextField(default='Kijuguta ward, Northern division, Kabale municipality, Uganda')),
                ('phone', models.CharField(default='+256 700 000 000', max_length=50)),
                ('email', models.EmailField(default='info@hopereceptioncentre.org', max_length=254)),
                ('mtn_mobile_money', models.CharField(default='+256 770 000 000 (Enid Origumusiriza)', max_length=50)),
                ('airtel_money', models.CharField(default='+256 750 000 000 (Rev. Michael Asiimwe)', max_length=50)),
                ('bank_details', models.TextField(default='Bank Name: Stanbic Bank Uganda\nAccount Name: Hope Reception Centre\nAccount No: 9030001234567\nBranch: Kabale Branch')),
                ('about_text', models.TextField(default='Hope Reception Centre was started in 2003 in Kabale Municipality to provide shelter, care, counseling, and education to vulnerable children.')),
                ('mission', models.TextField(default='To rehabilitate, empower, and restore hope to vulnerable and orphaned children through holistic care and counseling.')),
                ('vision', models.TextField(default='A society where every child is nurtured, protected, and empowered to reach their full potential.')),
            ],
        ),
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
