# Generated by Django 6.0.7 on 2026-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key identifier e.g. 'footer_disclaimer', 'homepage_welcome'", max_length=100, unique=True)),
                ('description', models.CharField(help_text='Description of where this text appears', max_length=255)),
                ('content', models.TextField(help_text='Custom text content editable word-by-word')),
            ],
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='anonymous_button_text',
            field=models.CharField(default='Get Anonymous Support', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='donate_button_text',
            field=models.CharField(default='Donate Now', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='emergency_counseling_heading',
            field=models.CharField(default='Emergency Counseling', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtext',
            field=models.CharField(default='Giving Hope to Vulnerable Children Since 2003', help_text='Subtitle under main heading', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Hope Reception Centre', help_text='Main heading on homepage hero banner', max_length=250),
        ),
    ]
