# Generated by Django 6.0.7 on 2026-07-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customtextsnippet_sitesetting_anonymous_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Background image for the homepage hero banner', null=True, upload_to='site_settings/'),
        ),
    ]
