# Generated by Django 6.0.7 on 2026-07-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-heart', help_text='FontAwesome icon class e.g. fa-hands-holding-child', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
