# Generated by Django 6.0.7 on 2026-07-29 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, help_text="Applicant's age", null=True)),
                ('reason', models.TextField(help_text='Why are you applying for this program?')),
                ('additional_info', models.TextField(blank=True, help_text="Any additional information you'd like to share", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes on this application', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program')),
            ],
            options={
                'verbose_name': 'Program Application',
                'verbose_name_plural': 'Program Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
