# Generated by Django 6.0.7 on 2026-07-29 19:52

import counseling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session', 'Counseling Session'), ('application', 'Program Application'), ('anonymous', 'Anonymous Message'), ('donation', 'Donation'), ('story', 'User Story'), ('contact', 'Contact Form'), ('live', 'Live Stream'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Admin URL to view this item', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='anonymousmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='anonymoussupportthread',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='counselingsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='anonymoussupportthread',
            name='token',
            field=models.CharField(default=counseling.models.generate_short_token, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='session_type',
            field=models.CharField(choices=[('individual', 'Individual Session'), ('group', 'Group Session'), ('digital', 'Digital / Online Session'), ('family', 'Family Session'), ('in_person', 'In-Person at Centre'), ('digital_video', 'Digital Video Session'), ('digital_text', 'Digital Text Session')], default='individual', max_length=30),
        ),
    ]
