# Generated by Django 6.0.7 on 2026-07-29 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the event or occasion', max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('cover_photo', models.ImageField(blank=True, help_text='Cover photo shown on gallery listing', null=True, upload_to='gallery/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Album',
                'verbose_name_plural': 'Event Albums',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Stories'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='media_centre.eventalbum')),
            ],
            options={
                'verbose_name': 'Album Photo',
                'verbose_name_plural': 'Album Photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
