# Generated by Django 6.0.7 on 2026-07-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_centre', '0002_eventalbum_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_sdp', models.TextField(blank=True, null=True)),
                ('is_broadcasting', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_signal', to='media_centre.video')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_token', models.CharField(max_length=64)),
                ('answer_sdp', models.TextField(blank=True, null=True)),
                ('broadcaster_ice', models.TextField(default='[]')),
                ('viewer_ice', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='media_centre.livestreamsignal')),
            ],
        ),
    ]
