# Generated by Django 6.0.7 on 2026-07-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_centre', '0003_livestreamsignal_viewerconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreamsignal',
            name='offer_sdp',
        ),
        migrations.AddField(
            model_name='viewerconnection',
            name='offer_sdp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
